### ISSUE TITLE
NLP (Non-Local Pooling)

### ISSUE THREAD

**Issue by wuxchcandoit** [jinxixiang/low_rank_wsi#2]
Hi! Thanks for your great work!
I wonder why there is a learnable variable named `S` in class `NLP`, namely `self.S= nn.Parameter(torch.Tensor(1, num_seeds, dim))`  because the paper mentions that a bag feature is obtained through max pooling over the output of ILRA layers. But in class `NLP`, it seems that the bag feature is learnable.

**Comment by jinxixiang** [comment]
thank you for your interest! To get the global feature for classification, we found both max-pooling and learning pooling are applicable. However learnable pooling is more stable across different datasets. Thus, this implementation is slightly different from the paper.
