### ISSUE TITLE
about the GAB block

### ISSUE THREAD

**Issue by shenxiaochenn** [jinxixiang/low_rank_wsi#3]
In line 44 of https://github.com/jinxixiang/low_rank_wsi/blob/main/mil/models/ilra.py, a residual connection seems to be implemented here. However, I don't find a corresponding operation in the appropriate place in the paper. I'm confused about this part. Thanks~~~

**Comment by jinxixiang** [comment]
Hi, it's a common practice to use residual connections with MHA.
