### ISSUE TITLE
Code for contrastive learning

### ISSUE THREAD

**Issue by Vison307** [jinxixiang/low_rank_wsi#4]
Thank you for the awesome work!

The idea of introducing the low-rank constraint (LRC) into contrastive learning is interesting. However, I could not find the code of contrastive learning in the code repo. Could you please provide the code?

**Comment by ElvinKim** [comment]
Did you receive the LRC code? I also need the LRC code.

**Comment by jinxixiang** [comment]
I appreciate your interest. The basic idea of LRC is to mine more positive samples for pathology images. The core code is from https://github.com/HobbitLong/SupContrast.
