### ISSUE TITLE
num_classes of dataset TCGA-NSCLC

### ISSUE THREAD

**Issue by wuxchcandoit** [jinxixiang/low_rank_wsi#5]
Hi! Thanks for your great work!
May I ask you a question?
Is the classification task for dataset TCGA-NSCLC still a binary classification task (the same as binary classification task for dataset CAMELYON16) even though the dataset TCGA-NSCLC includes two subtypes? I noticed that paper mentioned that 'TCGA-NSCLC includes two subtype projects (binary classification)'.

**Comment by jinxixiang** [comment]
Thank you, and yes, we did binary for TCGA-NSCLC
