### ISSUE TITLE
The number(rank) of the latent vectors(queries)

### ISSUE THREAD

**Issue by DonghweeYoon** [jinxixiang/low_rank_wsi#6]
Thank you for your interesting work!

I have read your code and found the ILRA-MIL aggregator has an argument named '**topK**'.
In the context of your paper, does topK argument correspond to the number(rank) of the latent vectors(queries)?

https://github.com/jinxixiang/low_rank_wsi/blob/8c6d56c803a838aaf9a8f875b8fb9e07fd53e72d/mil/models/ilra.py#L100-L122

Both GAB module and NLP module take 'topK' as an argument. I think two different variables should be used.

Thanks.

**Comment by jinxixiang** [comment]
Apologies for the delayed response!

Yes, the 'topk' in GAB is for the rank of the latent matrix, while the second 'topk' for output pooling. They are indeed two separate variables. The first 'topk', representing the rank, is tunable based on different applications. In contrast, the second 'topk' is always set to one. I’ve updated the repo by removing the second 'topk'.
