### ISSUE TITLE
Heatmap generation

### ISSUE THREAD

**Issue by ElvinKim** [jinxixiang/low_rank_wsi#7]
Hi! Thank you for your amazing work.

May I ask you a question?

I would like to inquire about how you drew the heatmap in Figure 4 of your paper.

(1) Did you use the heatmap generation code provided by the CLAM repo?
(1-1) If so, did you apply percentiles to the attention scores?

(2) It seems that all Normal(Non-Tumor) regions should appear blue, but they look transparent in your figure. Did you modify the code in any way?

**Comment by jinxixiang** [comment]
Hi, thank you for your feedback. We refactored the code from CLAM, and yes, we changed how it displays a bit. Since we are always concerned about the **red region**, we do some transparent effects for other areas.
