### ISSUE TITLE
Need help to understand the model

### ISSUE THREAD

**Issue by HHHedo** [jinxixiang/low_rank_wsi#8]
Thanks for your great work!
I have two questions and need your help!
1. The GAB (eq.16 in paper) is implemented as
https://github.com/jinxixiang/low_rank_wsi/blob/8c6d56c803a838aaf9a8f875b8fb9e07fd53e72d/mil/models/ilra.py#L50
while I think it should be `O = self.gate(O.mul(Q0))`
2. The same question as [issue #6](https://github.com/jinxixiang/low_rank_wsi/issues/6#issue-2232615082).

Thanks for your help!
Tiancheng

**Comment by jinxixiang** [comment]
Hi Tiancheng, apologies for the delayed response.

1. In the repo, it is a classic gating mechanism where the gate acts as a filter based on (Q0). Your suggestion introduces a more complex interaction between the output and the original input. I think both should work fine. 

2. Yes, the 'topk' in GAB is for the rank of the latent matrix, while the second 'topk' for output pooling. They are indeed two separate variables. The first 'topk', representing the rank, is tunable based on different applications. In contrast, the second 'topk' is always set to one. I’ve updated the repo by removing the second 'topk'

Apologies for any inconvenience caused.
